name: Update Stats, Snake, and Contribution Grid SVG

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-stats-snake-grid:
    name: Generate and Push Stats, Snake, and Contribution Grid SVG
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许写入 output 分支
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史记录

      - name: Clean untracked files
        run: |
          git clean -fd
          echo "Cleaned untracked files"

      - name: Generate Stats and Contribution Grid SVG
        run: |
          mkdir -p dist
          echo "Generating GitHub stats cards"
          curl -o dist/stats.svg "https://github-readme-stats.vercel.app/api?username=${{ github.repository_owner }}&show_icons=true&theme=radical&include_all_commits=true&count_private=true"
          curl -o dist/top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=${{ github.repository_owner }}&layout=compact&theme=radical"
          echo "Generating contribution grid SVG"
          curl -o dist/github-contribution-grid.svg "https://github-readme-stats.vercel.app/api?username=${{ github.repository_owner }}&show=contributions&include_all_commits=true&count_private=true&theme=radical"

      - name: Generate Contribution Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push SVG to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
